
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
        
    command: node dist/presentation/allBotsRun.js
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 15
    #   start_period: 10s
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  ad-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ad-worker
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: node dist/infrastructure/queue/workers/adWorker.js
    restart: unless-stopped

  queue-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: queue-scheduler
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    command: node dist/scripts/startQueues.js
    restart: unless-stopped

  group-user-sync-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: group-user-sync-scheduler
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    command: node -e "import('./dist/infrastructure/queue/groupUserSyncScheduler.js').then(m => m.scheduleGroupUserSync())"
    restart: unless-stopped

  invite-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invite-scheduler
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    command: node -e "import('./dist/infrastructure/queue/inviteScheduler.js').then(m => m.scheduleInviteJobs())"
    restart: unless-stopped

  target-sync-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: target-sync-scheduler
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    command: node -e "import('./dist/infrastructure/queue/syncTargetQueue.js').then(m => m.scheduleTargetGroupSync())"
    restart: unless-stopped

  target-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: target-worker
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: node dist/infrastructure/queue/workers/targetGroupSyncWorker.js
    restart: unless-stopped

  group-sync-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: group-sync-worker
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: node dist/infrastructure/queue/workers/groupUserSyncWorker.js
    restart: unless-stopped

  invite-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invite-worker
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: node dist/infrastructure/queue/workers/inviteWorker.js
    restart: unless-stopped

  bullboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-monitor
    command: node dist/monitor.js
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  postgres_data: